"""initial database

Revision ID: 4251eaf4786e
Revises: 271a07803374
Create Date: 2025-11-11 11:58:05.177875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4251eaf4786e'
down_revision = '271a07803374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training', sa.Column('paid_free', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training', 'paid_free')
    # ### end Alembic commands ###
